# Generated by Django 2.2.2 on 2020-02-04 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('info', models.TextField(verbose_name='Info')),
                ('image', models.ImageField(blank=True, upload_to='media/', verbose_name='image')),
                ('current_price', models.FloatField(default=0, verbose_name='Current price')),
                ('old_price', models.FloatField(default=0, verbose_name='Old Price')),
                ('category', models.ForeignKey(default='All categories', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_image', models.ImageField(blank=True, upload_to='media/', verbose_name='small image')),
                ('big_image', models.ImageField(blank=True, upload_to='media/', verbose_name='big image')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='shop.Goods')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='sub_category',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Subcategory'),
        ),
        migrations.AddField(
            model_name='category',
            name='sub_category',
            field=models.ManyToManyField(to='shop.Subcategory'),
        ),
    ]
