# Generated by Django 2.2.2 on 2020-01-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('info', models.TextField(verbose_name='Info')),
                ('image', models.ImageField(upload_to='media/', verbose_name='image')),
            ],
        ),
    ]
