# Generated by Django 2.2.2 on 2020-01-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='current_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='goods',
            name='old_price',
            field=models.FloatField(default=0),
        ),
    ]
