# Generated by Django 2.2.2 on 2020-01-30 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200130_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='image',
        ),
    ]
