# Generated by Django 2.2.2 on 2020-01-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_goods_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='media/', verbose_name='image'),
        ),
    ]
