# Generated by Django 2.2.2 on 2020-01-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200130_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.CharField(choices=[('All categories', 'All categories'), ('Cameras & Photography', 'Cameras & Photography'), ('Tv & Audio', 'Tv & Audio'), ('SmartPhones & Tablets', 'SmartPhones & Tablets'), ('Laptop & Computer', 'Laptop & Computer'), ('Sony', 'Sony'), ('Mobile', 'Mobile'), ('Sports', 'Sports'), ('Books', 'Books')], default='All categories', max_length=35),
        ),
    ]
