# Generated by Django 2.2.2 on 2020-01-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_goods_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='photos',
            field=models.ImageField(blank=True, default='', upload_to='media/', verbose_name='photo'),
        ),
    ]
