# Generated by Django 2.2.2 on 2020-01-31 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_goods_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='photos',
        ),
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.CharField(choices=[('All categories', 'All categories'), ('Cameras & Photography', 'Cameras & Photography'), ('Tv & Audio', 'Tv & Audio'), ('SmartPhones & Tablets', 'SmartPhones & Tablets'), ('Laptop & Computer', 'Laptop & Computer'), ('Sony', 'Sony'), ('Mobile', 'Mobile'), ('Sports', 'Sports'), ('Books', 'Books'), ('Speaker', 'Speaker')], default='All categories', max_length=35),
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='shop.Goods')),
            ],
        ),
    ]
