# Generated by Django 2.2.2 on 2020-01-31 19:31

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200131_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\F5\\PycharmProjects\\Shopio\\media'), upload_to='media/'),
        ),
    ]
