# Generated by Django 2.2.2 on 2020-02-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200131_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='image',
        ),
        migrations.AddField(
            model_name='photos',
            name='big_image',
            field=models.ImageField(blank=True, upload_to='media/', verbose_name='big image'),
        ),
        migrations.AddField(
            model_name='photos',
            name='small_image',
            field=models.ImageField(blank=True, upload_to='media/', verbose_name='small image'),
        ),
    ]
